spring:
  application:
    name: spring_ai_demo
  ai:
    ollama:
      chat:
        options:
          model: qwen3
      embedding:
        options:
          model: nomic-embed-text
      base-url: http://localhost:11434
    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8000
        collection-name: SpringAiCollection
        initialize-schema: true
    easy:
      enableRag: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  tomcat:
    max-swallow-size: 2MB
    disable-upload-timeout: false

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG